先进行一次进程状态的检查和启动, 再添加到定时任务
alibaba/havenask-federation pull request #60
Opened 2023-04-28 10:02 UTC by weizijun

确保started的时候，searcher、qrs进程已启动完成

2023-05-06 03:33 UTC, mushao999 requested changes

2023-05-06 03:33 UTC, mushao999 commented on modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
此处只是检查当发现searcher或qrs未启动时，发起启动操作，但是并未等待和检查searcher和qrs已经被成功拉起。因此仍然无法确保在sharded start时searcher和qrs已启动

2023-05-09 02:15 UTC, weizijun commented on modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
已加入循环检查，只有进程启动后才进入started状态

2023-05-09 03:14 UTC, mushao999 commented on modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
> +                runScript(startQrsCommand);
如果这里是阻塞执行的，那就没有问题

2023-05-09 03:14 UTC, mushao999 approved these changes

2023-05-09 03:17 UTC, weizijun commented on modules/havenask-engine/src/main/java/org/havenask/engine/NativeProcessControlService.java
> +                runScript(startQrsCommand);
是阻塞执行的，直到成功或者失败

2023-05-09 03:17 UTC, merged