支持havenask sql接口
alibaba/havenask-federation pull request #9
Opened 2023-04-10 07:29 UTC by weizijun

支持havenask sql接口。
可以通过`GET /_havenask/sql`接口，通过sql查询havenask数据

2023-04-10 11:23 UTC, mushao999 requested changes

2023-04-10 11:23 UTC, mushao999 commented on modules/havenask-engine/src/main/java/org/havenask/engine/search/action/TransportHavenaskSqlAction.java
> +            QrsSqlResponse result = qrsClient.executeSql(qrsSqlRequest);
这里是发起对qrs的请求，每个节点都可以执行吗？还是说只有在协调节点上？

2023-04-10 12:05 UTC, weizijun commented on modules/havenask-engine/src/main/java/org/havenask/engine/search/action/TransportHavenaskSqlAction.java
> +            QrsSqlResponse result = qrsClient.executeSql(qrsSqlRequest);
只在ingest节点执行，已添加转发相关逻辑

2023-04-11 02:09 UTC, mushao999 approved these changes
通过

2023-04-11 02:14 UTC, merged